#!/bin/bash

MYSQL_DATA_PATH=/mnt/mysql/data
MYSQL_PERSISTED_DATA_PATH=/test/compressed/mysql/data
#MYSQL_PERSISTED_DATA_PATH=/opt/ebs/mysql/data
MYSQL_MASTER_PORT=3306
MYSQL_SLAVE_PORT=13306
MYSQL_MASTER_SERVER_ID=1
MYSQL_SLAVE_SERVER_ID=2
MASTER_INNODB_BUFFER_POOL_SIZE=512M
SLAVE_INNODB_BUFFER_POOL_SIZE=256M
MYSQL_PASS=mypasswd
INNODB_USE_NATIVE_AIO=0
